### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by frankstallone** [RobinHerbots/jquery.inputmask#2581]
**Describe the bug**

In `5.0.7` we are experiencing a bug `ReferenceError: self is not defined` at runtime that we were not experiencing on `5.0.6`. No compilation errors. This is a node/React app. We're seeing the issue on our local machines and when deployed. It would appear 

```
/Users/<user>/.../<app>/node_modules/inputmask/dist/inputmask.js:13
}(self, (function() {
  ^

ReferenceError: self is not defined
    at Object.<anonymous> (/Users/<user>/.../<app>/node_modules/inputmask/dist/inputmask.js:13:3)
```

Maybe it has to do with `5.0.7`'s change to `}(self, (function() {`  from `5.0.6`'s `}(this, (function() {`?

**OS**

macOS & Linux

**Browser**

Latest Chrome/Safari/Firefox

**Inputmask version**

`5.0.7`

**Comment by RobinHerbots** [comment]
@frankstallone ,

Can you give some more context of how you import and build the app.  The self is added by webpack.

**Comment by frankstallone** [comment]
First of all, thank you for your response @RobinHerbots. We appreciate the great work you and the team here has done with `inputmask`!

This is a React app and we're importing this package into a few of our components in the component library. This is done with traditional import syntax, `import Inputmask from 'inputmask';`. Here is an example of how we're using it:

```js
Inputmask('datetime', {
    inputFormat: this.getInputFormat(),
    showMaskOnHover: false,
    showMaskOnFocus: false,
    placeholder: ' ',
    oncleared: () => (input.value = ''),
}).mask(input);
```

The app that uses these components is built with `webpack` and we're on version ~4. Is there some specific `webpack` config I can share that would be helpful here? I am going to continue to figure out more about this error and report back. Until then here is more from our log:

```bash
found this <ref *1> {
  '$$typeof': Symbol(react.context),
  _calculateChangedBits: null,
  _currentValue: { dispatch: [Function: dispatch], disabled: false },
  _currentValue2: { dispatch: [Function: dispatch], disabled: false },
  _threadCount: 0,
  Provider: { '$$typeof': Symbol(react.provider), _context: [Circular *1] },
  Consumer: {
    '$$typeof': Symbol(react.context),
    _context: [Circular *1],
    _calculateChangedBits: null
  },
  _currentRenderer: null,
  _currentRenderer2: null
}
/app/node_modules/inputmask/dist/inputmask.js:13
}(self, (function() {
  ^
ReferenceError: self is not defined
    at Object.<anonymous> (/app/node_modules/inputmask/dist/inputmask.js:13:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/app/node_modules/<internal-component-library>/ui-input/components/MaskedTimeInput.js:8:41)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/app/node_modules/<internal-component-library>/ui-input/components/AccordionMaskedTimeInput.js:11:24)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/app/node_modules/<internal-component-library>/ui-input/index.js:103:57)
```

**Comment by RobinHerbots** [comment]
@frankstallone ,

This is probably the problem.
https://webpack.js.org/configuration/output/#outputglobalobject

I will create a new build to see if this fixes the problem.

**Comment by frankstallone** [comment]
I think you are getting closer. What I am seeing is that our backend app is what is throwing the error. The backend app only uses our component library for typings (untraditional setup). That's running in Node, not in the browser window. Does that sound rediculous? I was having trouble trying to figure out how to articulate this.

**Comment by RobinHerbots** [comment]
@frankstallone ,

Can you have a try with  version 5.0.8-beta.1

**Comment by johnmcase** [comment]
I am seeing the same issue when trying to use Jest to unit tests web components I've developed that have a dependency on inputmask.  Jest uses a virtual DOM similar to react, so it makes sense I see the same error.

I can confirm that I do not get the error with 5.0.6.

I tried installing 5.0.8-beta.1 but NPM said that version does not exist.  Is there some other way we're supposed to install beta releases?

**Comment by frankstallone** [comment]
I have been meaning to give this a try @RobinHerbots — other priorities have been keeping me from it. I plan to do it tomorrow or Thursday. I think you can point to a GitHub repository for a package in `package.json` if it's not in the npm repository as `5.0.8-beta.1` @johnmcase. I'll find out soon enough myself. 😃

**Comment by RobinHerbots** [comment]
@johnmcase ,

I publisshed 5.0.8 beta 1 to npm

**Comment by frankstallone** [comment]
@RobinHerbots I can confirm `5.0.8-beta.1` does _not_ cause runtime errors in our app. 🎉

**Comment by RobinHerbots** [comment]
@frankstallone ,

Can you retest with version 5.0.8-beta.18.  As I made some changes to the webpack build which could have some impact.

**Comment by Burgov** [comment]
@RobinHerbots beta 18 doesn't appear to be published? I can confirm that the problem is resolved in beta 17 though.

**Comment by petercpwong** [comment]
Regression appearing again in `5.0.8-beta.25`

**Comment by akagamina** [comment]
this problem is continuing.

**Comment by zyasir** [comment]
> this problem is continuing.

Confirmed. I tried 5.0.8-beta.47 and 5.0.8-beta.25 but only 5.0.8-beta.1 works, so I'm using beta.1 for now.
