### ISSUE TITLE
Datetime mask `dd.mm.yyyy` issue replacing day field 

### ISSUE THREAD

**Issue by melloware** [RobinHerbots/jquery.inputmask#2813]
Original Bug Report at PrimeFaces: https://github.com/primefaces/primefaces/issues/12428

**InputMask:** 5.0.9 (but still fails with 5.10)

**Configuration:**
```js
{
alias: "datetime",
autoUnmask: false,
clearIncomplete: false,
clearMaskOnLostFocus: false,
inputFormat: "dd\/mm\/yyyy HH:MM:ss",
placeholder: "_",
showMaskOnHover: false,
 }
```

1. Click into datePicker input field
2. Put the cursor at the beginning of the field
3. Type "12" to try and set the day to 12
4. Observe the stack trace

CodePen: https://codepen.io/melloware/pen/zYVddzY

```
Uncaught RangeError: Maximum call stack size exceeded
    at y.h (jquery.inputmask.min.js:8:99582)
    at y.p (jquery.inputmask.min.js:8:99052)
    at y.f (jquery.inputmask.min.js:8:98414)
    at jquery.inputmask.min.js:8:105270
    at y.h (jquery.inputmask.min.js:8:105517)
    at y.p (jquery.inputmask.min.js:8:99052)
    at y.f (jquery.inputmask.min.js:8:98414)
    at jquery.inputmask.min.js:8:105270
    at y.h (jquery.inputmask.min.js:8:105517)
    at y.p (jquery.inputmask.min.js:8:99052)
```

**Comment by raphisuter** [comment]
+1

**Comment by t0mmysenf** [comment]
+1

**Comment by mn-qualitasag** [comment]
+1

**Comment by mertsincan** [comment]
+1

**Comment by RobinHerbots** [comment]
See #2814
